name: Nightly Release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: photostructure/git-ssh-signing-action@v2
        with:
          ssh-signing-key: ${{ secrets.SSH_SIGNING_KEY }}
          git-user-name: ${{ secrets.GIT_USER_NAME }}
          git-user-email: ${{ secrets.GIT_USER_EMAIL }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Run release script
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          set +e
          VERSION=$(python3 .github/scripts/release.py)
          if [[ -n "${VERSION}" ]] ; then
            git add .
            git commit --no-gpg-sign -m "chore: release ${VERSION}"
            git tag --no-sign -a "release/${VERSION}" -m "Release ${VERSION}"
            git push origin main
            git push origin --tags
          fi

